version: "3.5"
services:
  mpd:
    build: fake_mpd/
    volumes:
      - ./fake_mpd/music:/var/lib/mpd/music
      - ./fake_mpd/playlists:/var/lib/mpd/playlists
    ports:
      - 6600 # MPD protocol

  redis:
    image: redis:latest
    ports: 
     - 6379

  art:
    build: art/
    environment:
      MPD_HOST: mpd
    volumes:
      - ./fake_mpd/music:/data/music
      - ./fake_mpd/store:/data/store
    ports:
      - 5001:80

  listener:
    build: listener/
    environment:
      MPD_HOST: mpd
      REDIS_HOST: redis

  web:
    build: web/
    environment:
      REDIS_HOST: redis
      MPD_HOST: mpd
      ALBUM_ART_URL: localhost:5001
    volumes:
      - ./web/dist/remote.js:/code/remote/static/dist/remote.js
    ports:
      - 5000:80
