services:
  mpd:
    build: fake_mpd/
    volumes:
      - ./fake_mpd/mpd.conf:/etc/mpd.conf
      - ./fake_mpd/music:/var/lib/mpd/music
      - ./fake_mpd/playlists:/var/lib/mpd/playlists
    ports:
      - 6600:6600 # MPD protocol
  proxy:
    build: 
      context: mpd-web-proxy/
      args:
        BUILD_VERSION: 
    environment:
      MPD_AUTHORITY: mpd:6600
      PROXY_PIN_FILE: /app/pins.yaml
      PROXY_MUSIC_DIR: /var/lib/mpd/music
    volumes:
      - ./mpd-web-proxy/pins.yaml:/app/pins.yaml
      - ./fake_mpd/music:/var/lib/mpd/music
    ports:
      - 8000
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static/index.html:/www/data/static/index.html:ro
      - ./web/dist:/www/data/static/dist:ro
      - ./art/remote_art/static/notfound.png:/www/data/static/notfound.png:ro
    ports:
      - 80:80
