services:
  mpd:
    build: fake_mpd/
    volumes:
      - ./fake_mpd/mpd.conf:/etc/mpd.conf
      - ./fake_mpd/music:/var/lib/mpd/music
      - ./fake_mpd/playlists:/var/lib/mpd/playlists
    ports:
      - 6600:6600 # MPD protocol
  art:
    build: art/
    environment:
      MPD_HOST: mpd
    volumes:
      - ./fake_mpd/music:/data/music
      - ./fake_mpd/store:/data/store
    ports:
      - 80
  proxy:
    build: mpd-web-proxy/
    environment:
      MPD_AUTHORITY: mpd:6600
    volumes:
      - ./mpd-web-proxy/pins.yaml:/app/pins.yaml
    ports:
      - 8000
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static/index.html:/www/data/static/index.html:ro
      - ./web/dist:/www/data/static/dist:ro
      - ./art/remote_art/static/notfound.png:/www/data/static/notfound.png:ro
    ports:
      - 80:80
