version: "3.5"
services:
  mpd:
    image: fake-mpd:latest
    volumes:
      - ./fake_mpd/music:/var/lib/mpd/music
      - ./fake_mpd/playlists:/var/lib/mpd/playlists
    ports:
      - "6600" # MPD protocol
