version: "3.3"

services:
    remote-listener:
        build: .
        environment:
            MPD_HOST: 192.168.2.5
            REDIS_HOST: redis
        volumes:
            - ./src/main.py:/code/main.py


networks:
    default:
        external:
            name: remote
