# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release 

jobs:
  build-frontend:
    on:
      push:
        branches:
          - '*'
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

# -- Frontend Actions --
    - name: Set Up Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install node deps
      working-directory: ./web
      run: npm i -g yarn && yarn

    - name: Build Frontend
      working-directory: ./web
      run: yarn build

  release:
    on:
      push:
        tags:
          - '*'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

# -- Frontend Actions --
    - name: Set Up Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install node deps
      working-directory: ./web
      run: npm i -g yarn && yarn

    - name: Build Frontend
      working-directory: ./web
      run: yarn build

# -- Go actions --
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build-Arm
      working-directory: ./mpd-web-proxy
      env:
        GOARCH: arm
      run: go build -o mpd-web-proxy-arm -v . && gzip mpd-web-proxy-arm


# -- Release --
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mpd-web-proxy/mpd-web-proxy-arm.gz
        asset_name: mpd-web-proxy-arm.gz
        asset_content_type: application/gzip

