name: Create Release

on:
  push:
    tags: ['*']

# -- Release --
jobs:
  release:
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mpd-web-proxy/mpd-web-proxy-arm.gz
        asset_name: mpd-web-proxy-arm.gz
        asset_content_type: application/gzip

